global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'torchserve'
    static_configs:
      - targets: ['torchserve:8082']
    metrics_path: '/metrics'
    scrape_interval: 15s 